### PR TITLE
Allow an array of pandocOptions

### LINKED ISSUE #5: Arguments with spaces in them are not supported
I'm trying to pass a title string like `-T "this is the title"`. You are splitting on space characters so `"this` is passed as one argument, `is` as another and so on. Might I suggest allowing an array of options to be passed, instead of a string?

### PR DESCRIPTION
**Pull request by tremby**
This fixes #5.

I haven't looked at writing/editing tests, since the existing tests on your master branch fail.

### CODE REVIEW

**Comment by gmp26** [comment]
Thanks Bart. I'll take a look.

**Comment by gmp26** [comment]
Tests are passing for me. Can you give me more detail?

**Comment by gmp26** [comment]
OK. Tests pass here with your changes, and it has not broken my use-case so I'm merging and republishing on npm.

**Comment by tremby** [comment]
My mistake. The machine it was failing on didn't have tex installed so the PDF gen was failing. This calls for another ticket...

**Pull request merged**
